#Ubuntu 12.04 precise
#Vagrantfile

$script = <<SCRIPT
	echo I am provisioning...
	date > /etc/vagrant_provisioned_at
	sudo apt-get install lxc wget bsdtar curl
	sudo apt-get install linux-image-extra-`uname -r`
	wget http://get.docker.io/builds/$(uname -s)/$(uname -m)/docker-master.tgz
	tar -xf docker-master.tgz
	PATH=$PATH:$HOME/docker-master
	cd docker-master
	sudo ./docker run -i -t base /bin/bash
SCRIPT

VAGRANTFILE_API_VERSION = "2"

box 	 = 'precise32'
hostname = 'precisebox-quantza'
url 	 = 'http://files.vagrantup.com/precise32.box'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.boot_timeout = 60
  config.vm.box = box
  config.vm.box_url = url
  #config.vm.graceful_halt_timeout = 240
  config.vm.hostname = hostname
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 22, host: 22
  config.vm.provision "shell", inline: $script
end